### ISSUE TITLE
Contas a Receber em Aberto de um Contato Específico

### ISSUE THREAD

**Issue by leobaldoneto** [AlexandreBellas/bling-erp-api-js#26]
Olá, tudo bem? Estou com uma dúvida em relação a API do Bling e gostaria de saber se vocês podem dar uma luz.

Preciso listar as Contas a Receber de um contato específico, porém vi que o endepoint de Contas a Receber não possui nenhum método ou parâmetro que permita filtrar pelo contato.

Uma forma alternativa que tentei fazer foi pegar o id do contato > listar os pedidos do contato > pegar cada pedido de forma completa > verificar parcelas do pedido > pegar id de cada parcela > ❌ pegar cada conta a receber pelo id da parcela ❌
O problema: o id da parcela do pedido e da conta a receber são entidades diferentes e com ids diferentes.

Dessa forma, acredito que não há como atingir o objetivo usando somente a API. Há algo que estou deixando passar?

A última alternativa que tenho em mente é de sincronizar/baixar todas as contas a receber do Bling para um banco de dados local e fazer as operações a partir dele. Seria esse o único caminho?

Desde já, agradeço.

**Comment by AlexandreBellas** [comment]
Fala @leobaldoneto! Peço perdão por não te responder mais cedo.

Imagino que você possa criar uma categoria de receitas e despesas para cada contato, e aí você atribui para cada conta a receber. Dessa forma você conseguiria filtrar pela API. Se não for assim, não consigo ver outra forma a não ser baixar para um banco de dados local como você comentou, só que o trabalho se tornaria bem maior.

Você chegou a encontrar alguma alternativa?

**Comment by leobaldoneto** [comment]
> Fala @leobaldoneto! Peço perdão por não te responder mais cedo.
> 
> Imagino que você possa criar uma categoria de receitas e despesas para cada contato, e aí você atribui para cada conta a receber. Dessa forma você conseguiria filtrar pela API. Se não for assim, não consigo ver outra forma a não ser baixar para um banco de dados local como você comentou, só que o trabalho se tornaria bem maior.
> 
> Você chegou a encontrar alguma alternativa?

Sem problemas. Agradeço a ideia, mas acredito que dessa forma seria inviável, pois são centenas de contas. A solução pelo jeito vai ser implementar um banco de dados para relatórios e rotinas de sincronização. Eles limitam bastante a API para evitar muito tráfego.

**Comment by AlexandreBellas** [comment]
Entendi. Se fosse possível criar automaticamente as categorias resolveria o problema, mas é uma pena que a API ainda está limitada nisso.

Em seu lugar, por ora seguiria o mesmo caminho que você comentou.

**Comment by leobaldoneto** [comment]
Realmente. Outro problema seria disso seria que iria poluir muito as categorias, atrapalhando a usabilidade e os relatórios financeiros. 

Quando eu tiver concluído a solução, chamo por aqui. Obrigado!
